name: insomnia_checklist
description: Checklist for better sleep

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS   versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.7+10

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
#  flutter_vector_icons: ^1.0.0
#  font_awesome_flutter: ^9.0.0
#  ionicons: ^0.1.2
#  eva_icons_flutter: ^3.0.0
#  fluentui_system_icons: ^1.1.115
#  fluttericon: ^2.0.0
#  crypto_font_icons: 1.0.0+1
#  simple_icons: ^4.17.0
#  flutter_tabler_icons: ^1.0.3-rc.1
  alert_dialogs: #0.2.0
    git:
      url: https://github.com/bizz84/codewithandrea_flutter_packages
      path: packages/alert_dialogs
  custom_buttons: #0.1.0
    git:
      url: https://github.com/bizz84/codewithandrea_flutter_packages
      path: packages/custom_buttons
  email_password_sign_in_ui: # 0.3.0
    git:
      url: https://github.com/bizz84/codewithandrea_flutter_packages
      path: packages/email_password_sign_in_ui
#  firestore_service: # 0.2.0
#    git:
#     url: https://github.com/bizz84/codewithandrea_flutter_packages
#      path: packages/firestore_service
  cloud_firestore: ^3.1.11
#  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  firebase_auth: ^1.0.0
  firebase_core: ^1.14.0
#  provider: ^5.0.0
  flutter_riverpod: ^1.0.3
  flutter_svg: ^1.0.3
  intl: ^0.17.0
  logger: ^1.1.0
  rxdart: ^0.27.3
  shared_preferences: ^2.0.13
#  state_notifier: ^0.7.2+1
#  entry: ^0.0.2+2
  flutter_rating_bar: ^4.0.0
  exif: ^3.1.1
  url_launcher: ^6.0.20
#  month_picker_dialog: ^0.4.0
#  flutter_date_pickers: ^0.3.0
  month_year_picker: ^0.1.0+1
  flutter_staggered_grid_view: ^0.4.0
  reorderables: ^0.4.3
#  freezed: ^0.14.0
  firebase_auth_mocks: ^0.7.1
  fake_cloud_firestore: ^1.2.2
#  flutter_portal: ^0.4.0
#  flutter_native_splash: ^2.1.2+1
#  os_detect: ^2.0.0



dev_dependencies:
#  flutter_launcher_icons: "^0.9.2"
#  flutter_app_name: ^0.1.0
#  mockito: ^5.1.0
#  random_string: ^2.3.1
  test: ^1.17.12
#  flutter_native_splash: ^2.1.2+1
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

#  flutter pub run flutter_app_name
flutter_app_name:
  name: "Sleeptracker"



flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/appIcon/icon.jpg"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/time-tracking.svg
    - assets/
    - assets/products/
    - assets/products/product1.jpg
    - assets/products/product2.jpg
    - assets/products/product3.jpg
    - assets/products/product4.jpg
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_native_splash:
  color: "#42a5f5"